export const testData = [
    // Dairy (A01-A08)
    {
      uniqueID: "A01",
      mainCategory: "Dairy",
      subCategory: "Fresh Milk",
      name: "Whole Milk",
      unit: "l",
      description: "Farm fresh milk from Wisconsin",
    },
    {
      uniqueID: "A02",
      mainCategory: "Dairy",
      subCategory: "Cheese",
      name: "Cheddar Cheese",
      unit: "kg",
      description: "Aged cheddar crafted in Vermont",
    },
    {
      uniqueID: "A03",
      mainCategory: "Dairy",
      subCategory: "Butter",
      name: "Unsalted Butter",
      unit: "kg",
      description: "Creamy butter produced in Normandy",
    },
    {
      uniqueID: "A04",
      mainCategory: "Dairy",
      subCategory: "Yogurt",
      name: "Greek Yogurt",
      unit: "l",
      description: "Tangy yogurt imported from Greece",
    },
    {
      uniqueID: "A05",
      mainCategory: "Dairy",
      subCategory: "Cream",
      name: "Heavy Cream",
      unit: "l",
      description: "Rich cream made in France",
    },
    {
      uniqueID: "A06",
      mainCategory: "Dairy",
      subCategory: "Plant-Based Milk",
      name: "Almond Milk",
      unit: "l",
      description: "Smooth almond milk from California",
    },
    {
      uniqueID: "A07",
      mainCategory: "Dairy",
      subCategory: "Fresh Milk",
      name: "Low Fat Milk",
      unit: "l",
      description: "Skim milk produced locally",
    },
    {
      uniqueID: "A08",
      mainCategory: "Dairy",
      subCategory: "Cheese",
      name: "Mozzarella Cheese",
      unit: "kg",
      description: "Soft cheese imported from Italy",
    },
  
    // Grains & Cereals (B01-B08)
    {
      uniqueID: "B01",
      mainCategory: "Grains & Cereals",
      subCategory: "Flour",
      name: "Whole Wheat Flour",
      unit: "kg",
      description: "Milled in the USA with tradition",
    },
    {
      uniqueID: "B02",
      mainCategory: "Grains & Cereals",
      subCategory: "Rice",
      name: "Basmati Rice",
      unit: "kg",
      description: "Long-grain rice cultivated in India",
    },
    {
      uniqueID: "B03",
      mainCategory: "Grains & Cereals",
      subCategory: "Noodles",
      name: "Egg Noodles",
      unit: "kg",
      description: "Handmade noodles from Taiwan",
    },
    {
      uniqueID: "B04",
      mainCategory: "Grains & Cereals",
      subCategory: "Pasta",
      name: "Spaghetti Pasta",
      unit: "kg",
      description: "Authentic pasta imported from Italy",
    },
    {
      uniqueID: "B05",
      mainCategory: "Grains & Cereals",
      subCategory: "Oats",
      name: "Rolled Oats",
      unit: "kg",
      description: "Organic oats sourced from Scotland",
    },
    {
      uniqueID: "B06",
      mainCategory: "Grains & Cereals",
      subCategory: "Barley",
      name: "Pearl Barley",
      unit: "kg",
      description: "Cultivated barley grown in Canada",
    },
    {
      uniqueID: "B07",
      mainCategory: "Grains & Cereals",
      subCategory: "Cornmeal",
      name: "Fine Cornmeal",
      unit: "kg",
      description: "Ground cornmeal produced in Mexico",
    },
    {
      uniqueID: "B08",
      mainCategory: "Grains & Cereals",
      subCategory: "Rice",
      name: "Jasmine Rice",
      unit: "kg",
      description: "Aromatic rice from the fields of Thailand",
    },
  
    // Meat (C01-C08)
    {
      uniqueID: "C01",
      mainCategory: "Meat",
      subCategory: "Pork",
      name: "Pork Shoulder",
      unit: "kg",
      description: "Succulent pork shoulder from Germany",
    },
    {
      uniqueID: "C02",
      mainCategory: "Meat",
      subCategory: "Beef",
      name: "Beef Ribeye",
      unit: "kg",
      description: "Grass-fed ribeye raised in Argentina",
    },
    {
      uniqueID: "C03",
      mainCategory: "Meat",
      subCategory: "Chicken",
      name: "Chicken Breast",
      unit: "kg",
      description: "Tender chicken breast from Spain",
    },
    {
      uniqueID: "C04",
      mainCategory: "Meat",
      subCategory: "Duck",
      name: "Duck Breast",
      unit: "kg",
      description: "Premium duck breast sourced from France",
    },
    {
      uniqueID: "C05",
      mainCategory: "Meat",
      subCategory: "Fish",
      name: "Salmon Fillet",
      unit: "kg",
      description: "Wild-caught salmon from the cold seas of Norway",
    },
    {
      uniqueID: "C06",
      mainCategory: "Meat",
      subCategory: "Lamb",
      name: "Lamb Chop",
      unit: "kg",
      description: "Farm-raised lamb chop from New Zealand",
    },
    {
      uniqueID: "C07",
      mainCategory: "Meat",
      subCategory: "Seafood",
      name: "Shrimp Medley",
      unit: "kg",
      description: "Assorted shrimp fresh from the Gulf",
    },
    {
      uniqueID: "C08",
      mainCategory: "Meat",
      subCategory: "Chicken",
      name: "Chicken Drumstick",
      unit: "kg",
      description: "Juicy drumstick sourced from Brazil",
    },
  
    // Seasonings (D01-D08)
    {
      uniqueID: "D01",
      mainCategory: "Seasonings",
      subCategory: "Salt",
      name: "Sea Salt",
      unit: "kg",
      description: "Harvested from the Mediterranean Sea",
    },
    {
      uniqueID: "D02",
      mainCategory: "Seasonings",
      subCategory: "Sugar",
      name: "Organic Brown Sugar",
      unit: "kg",
      description: "Refined from sugarcane in Brazil",
    },
    {
      uniqueID: "D03",
      mainCategory: "Seasonings",
      subCategory: "Pepper",
      name: "Ground Black Pepper",
      unit: "kg",
      description: "Spiced and dried in the spice markets of India",
    },
    {
      uniqueID: "D04",
      mainCategory: "Seasonings",
      subCategory: "Soy Sauce",
      name: "Premium Dark Soy Sauce",
      unit: "l",
      description: "Fermented with care in Japan",
    },
    {
      uniqueID: "D05",
      mainCategory: "Seasonings",
      subCategory: "Vinegar",
      name: "Italian Balsamic Vinegar",
      unit: "l",
      description: "Aged in Modena for exquisite flavor",
    },
    {
      uniqueID: "D06",
      mainCategory: "Seasonings",
      subCategory: "Chili Flakes",
      name: "Spicy Red Chili Flakes",
      unit: "kg",
      description: "Dried under the Mexican sun for bold heat",
    },
    {
      uniqueID: "D07",
      mainCategory: "Seasonings",
      subCategory: "Garlic Powder",
      name: "Smoked Garlic Powder",
      unit: "kg",
      description: "Infused with a hint of natural smoke",
    },
    {
      uniqueID: "D08",
      mainCategory: "Seasonings",
      subCategory: "Salt",
      name: "Himalayan Salt",
      unit: "kg",
      description: "Mined from ancient Himalayan deposits",
    },
  
    // Vegetable & Fruits (E01-E08)
    {
      uniqueID: "E01",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Leafy Greens",
      name: "Fresh Spinach",
      unit: "kg",
      description: "Crisp greens harvested from California farms",
    },
    {
      uniqueID: "E02",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Root Vegetables",
      name: "Organic Carrots",
      unit: "kg",
      description: "Vibrant carrots grown in Ontario",
    },
    {
      uniqueID: "E03",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Fruit Vegetables",
      name: "Vine Ripe Tomatoes",
      unit: "kg",
      description: "Sun-kissed tomatoes cultivated in Spain",
    },
    {
      uniqueID: "E04",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Cruciferous Vegetables",
      name: "Crisp Broccoli",
      unit: "kg",
      description: "Locally grown broccoli with a fresh crunch",
    },
    {
      uniqueID: "E05",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Citrus",
      name: "Juicy Oranges",
      unit: "l",
      description: "Citrus burst from Florida groves",
    },
    {
      uniqueID: "E06",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Berries",
      name: "Sweet Strawberries",
      unit: "kg",
      description: "Plump strawberries cultivated in the Netherlands",
    },
    {
      uniqueID: "E07",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Tropical Fruits",
      name: "Ripe Mangoes",
      unit: "kg",
      description: "Exotic mangoes bursting with tropical flavor from India",
    },
    {
      uniqueID: "E08",
      mainCategory: "Vegetable & Fruits",
      subCategory: "Leafy Greens",
      name: "Fresh Lettuce",
      unit: "kg",
      description: "Cool, crisp lettuce sourced from Mexico",
    },
  ];



const loop = (data) =>{
  let array = [];
  data.map((i)=>{
    array.push(i.name)
  })

  return array
} 


console.log(loop(testData))